### ISSUE TITLE
I provide an interface, Support YY.com

### ISSUE THREAD

**Issue by lki2019** [beardypig/streamlink-portable#10]
@fozzy 

Are you a member of the streamlink development community?

I provide an interface, Support YY.com

http://ctapis.wowolives.com/index.aspx?m=getyld&s=room number

example：http://www.yy.com/22490906

http://ctapis.wowolives.com/index.aspx?m=getyld&s=22490906      【submit】

http://hls.huanjuyun.com/newlive/22490906_22490906.m3u8?org=web&appid=0&uuid=b2e60b06812e487aa7916faf6c85d6b7&t=1501643650&tk=474e65974b8b9dcf6f4bee8d2043cbe7&uid=0

**Comment by lki2019** [comment]
http://i1.ciimg.com/1949/46906e01b6235114.png

**Comment by lki2019** [comment]
Thank you for helping me so much before!

**Comment by beardypig** [comment]
@lki2019 you should post this over on the Streamlink repo: https://github.com/streamlink/streamlink/ as this issue doesn't not relate to this portable version.

**Comment by ACmagic** [comment]
@lki2019 Can you please advise how you implement this interface?
