### ISSUE TITLE
Nightly Version Woes

### ISSUE THREAD

**Issue by dojima** [beardypig/streamlink-portable#15]
Similar to the issue I opened [here](https://github.com/streamlink/streamlink-twitch-gui/issues/591), I'm unable to make Streamlink Twitch GUI work with the current Streamlink Portable nightly I think because of a versioning error.  `streamlink -V` produces `0+untagged.112.g965c375`.  If this is the expected output, and it's a matter of Streamlink Twitch GUI not liking it, I'll be happy to reopen my original issue there.

Thanks for any assistance.

**Comment by beardypig** [comment]
Thanks for the bug report. The version shouldn't be `0+...`, I will take a look :) Probably some change for `versioneer` that I didn't take in to account for the nightlies.

**Comment by beardypig** [comment]
Should be resolved as of f590ebf1bf65e5e24dee15a73a3e4cef52e5d14d.

Same thing happened in the regular streamlink releases and was resolved in https://github.com/streamlink/streamlink/pull/2094.
