### ISSUE TITLE
Latest Nightly build release failed...

### ISSUE THREAD

**Issue by Vangelis66** [beardypig/streamlink-portable#18]
Happy New Year @beardypig 😄 

I am watching the **Nightly portable build** releases since a while ago and 
just became aware that the usual, daily, GitHub e-mail titled 
`[beardypig/streamlink-portable] Pre-release latest - Nightly Build` 
from `github-actions[bot]` is AWOL... 😞 
That would've been announcing the availability of 
`streamlink-portable-2.0.0+16.g7b74974-py3.6.5-win32.zip`

I browsed the **Actions** tab and regrettably saw that the build creation has failed: 

![SL-Nightly_fail](https://user-images.githubusercontent.com/9669492/103470047-c4036000-4d75-11eb-8207-7136c0dcce5b.JPG)

Perhaps recent repo activity has somehow broken things? 
These portable builds of yours are **highly appreciated** 👍 , as the other portable streamlink package has been sadly abandoned 😭 ...

While I'm at it, would you mind if I asked some related questions?
1. PSF has 3.6.**8**-win32 binaries available, can these be used instead of 3.6.**5**?
2. Would it be hard to move to latest py3.7 (**3.7.9** to be exact)?
3. What is the underlying reason some modules are "frozen" at older versions (e.g. pycryptodome-3.**4.3** used, latest being 3.**9.9**)?

Many thanks, my heartfelt wishes for 2021, stay healthy and safe wherever you happen to be...

**Comment by beardypig** [comment]
Yes, it broke. I noticed it broke and took a look, but I didn't see a way to fix it quickly. I planned to look at it tomorrow. 

Updating to 3.7.9 is easy and I will do it.  

The versions were frozen at the time when I made it to maintain compatibility pre-2.0.0, they could be updated now to match the current versions used by streamlink 2.0.0.

**Comment by beardypig** [comment]
I have updated the Python version and the dependencies, I just need to fix that pesky nightly build issue.

**Comment by beardypig** [comment]
For some reason the merge commit was making the auto-release fail.

**Comment by Vangelis66** [comment]
I'm sorry to spoil it again for you, ... but the archive's filename still mentions Python **3.6.5** :

![NR](https://user-images.githubusercontent.com/9669492/103492975-528be600-4e37-11eb-9ef8-db7869f7470c.JPG)

**Comment by Vangelis66** [comment]
... And does still contain **Python 3.6.5** in its guts: 

![py365](https://user-images.githubusercontent.com/9669492/103493274-f88c2000-4e38-11eb-8945-af621250a26a.JPG)

I think I have opened a can of worms... :disappointed:

**Comment by beardypig** [comment]
Actually for real will be 3.7.9, forgot it set the Python version in the action workflow too...

**Comment by Vangelis66** [comment]
Thanks... at long last! :tada: 
Apologies I made you work overtime/overnight... :smiley: 

One last thing: 
`__pycache__` folders inside the new py**3.7.9** archive (`.streamlink/packages/*`) **still contain** compiled files (*.pyc) from py3.**6.5**, also some other remnant files reference **py3.6**, should these be removed or will cause no harm?

![P1](https://user-images.githubusercontent.com/9669492/103494044-92ee6280-4e3d-11eb-8e9d-5683380d49a0.JPG) ![P2](https://user-images.githubusercontent.com/9669492/103494054-9a157080-4e3d-11eb-8c1e-016d4a559cfb.JPG)

**Comment by beardypig** [comment]
That's weird, maybe from caching on github... they shouldn't do any harm though and will probably disappear in a couple of days worth of nightly builds anyway.

**Comment by Vangelis66** [comment]
> `__pycache__` folders inside the new py**3.7.9** archive (`./streamlink/packages/*`) **_still_** contain compiled files (*.pyc) from py**3.6.5**, also some other remnant files reference py**3.6**,

I see now this was, most probably, addressed by https://github.com/beardypig/streamlink-portable/commit/612b929ca350f1e17e71887843de72b1afd0b8f4 :+1: 
Thanks for your perseverance! :smile:

**Comment by beardypig** [comment]
yeah it probably was that :)
