### ISSUE TITLE
Stable releases are still being built with Python 3.6.5

### ISSUE THREAD

**Issue by Vangelis66** [beardypig/streamlink-portable#20]
As always, many thanks for offering and maintaining this **portable** edition of `streamlink` :+1: ; it's the _only_ version of `streamlink` I ever use...
In https://github.com/beardypig/streamlink-portable/commit/00749dff6b82096955a70193f865f0b43ccaed02, one gets the impression (by the commit's title) **all** portable packages (nightly+**release**) have been updated to **Python 3.7.9**, but upon closer inspection of the latest **stable** release, **[2.1.0](https://github.com/beardypig/streamlink-portable/releases/tag/2.1.0)** (with **2.1.1**, no doubt, on the way :wink:.), one sees it is _still_ built on **Python 3.6.5** ...

Referenced commit only touched the **nightly workflow file** (.github/workflows/nightly.yml), but not the [release](https://github.com/beardypig/streamlink-portable/blob/master/.github/workflows/release.yml) one, hence the discrepancy... Was that just an _omission_ or a _deliberate decision_ to "freeze" release packages on **py3.6**? 

Thanks in advance for any insight, best wishes! :smile: 

OT (slightly) : A [third party](https://github.com/adang1345/PythonWindows) has been compiling and offering **Windows builds** of Python versions under **security-only** maintenance (i.e. Python versions for which the **PSF** _do not_ provide binaries), I have tried myself v3.6.**13** (from [here](https://github.com/adang1345/PythonWindows/blob/master/3.6.13/python-3.6.13-embed-win32.zip)) with the **release** packages (overwriting the 3.6.5 files) and v3.7.**10** (from [here](https://github.com/adang1345/PythonWindows/blob/master/3.7.10/python-3.7.10-embed-win32.zip)) with the **nightly** packages (overwriting the 3.7.9 files), I have encountered no issues whatsoever with them! Just as a FYI for users feeling adventurous... :wink:

**Comment by beardypig** [comment]
Yeah, may have messed that up... checking. (sorry for late reply)

**Comment by Vangelis66** [comment]
Thanks for looking into this 👍 ; I actually don't mind the tardy reply, 
I mostly use the **Nightly channel** myself... 😉 

FWIW, latest release **2.1.1** was recompiled **6 hours ago** by GA, but it's still **py3.6** based: 
https://github.com/beardypig/streamlink-portable/releases/tag/2.1.1

OTOH, the latest "**release**" workflow run 
https://github.com/beardypig/streamlink-portable/runs/2592554057
succeeded, but did not produce (yet?) any **py3.7** packages... 
Does that mean that one'll have to wait for the next SL release (**2.1.2**?) for the **Python 3.7.9** portable bundle?

**Comment by beardypig** [comment]
Because those actions are on a schedule I need to wait until it ran again to reload the new workflow, hopefully the next run should generate a py3.7 version :)

**Comment by Vangelis66** [comment]
OK, the latest **stable release** (**2.1.1**) portable package has been recompiled bundled with **Python 3.7.9** and re-released on 
https://github.com/beardypig/streamlink-portable/releases/tag/2.1.1
Thanks for your support! 👍 🎉 Hence, I'm closing this issue now...

Take care, best wishes 😄
