### ISSUE TITLE
Portable nightlies : Latest changes not included

### ISSUE THREAD

**Issue by karlo2105** [beardypig/streamlink-portable#4]
I would like to point out your portable version didn't include the latest Streamlink merging changes. 
For instance ceskatelevize plugin is not included.

**Comment by beardypig** [comment]
Unfortunately the latest portable build was made before that was merged, the commit that it was built from was [3253063](https://github.com/streamlink/streamlink/commit/3253063cf82abac21b98da0fc83712303978adb8). 

The nightly is only built once per day, at around 17:00 UTC - it's not easy to control when travis schedules it thought. I might go back to triggering the build every hour via a cron job on my server.

**Comment by karlo2105** [comment]
I thought it was automatically built when the latest changes are committed to master.

**Comment by beardypig** [comment]
No, there is no link between the build of streamlink and the build of streamlink-portable, unfortunately.

**Comment by beardypig** [comment]
I have updated my trigger build script and set it to run every 5 minutes, so the portable builds should only be 5 minutes behind the latest commit on streamlink.
