### ISSUE TITLE
Getting the portable version to work with Daisuki.net

### ISSUE THREAD

**Issue by starchivore** [beardypig/streamlink-portable#7]
Good Day,

I've been using this [Daisuki](http://www.daisuki.net/us/en/anime/watch.DRAGONBALLSUPERUniverseSurvivalsaga.16137.html) plugin for many months:

[https://gist.github.com/intact/3d6af5f361c1a44fd878](https://gist.github.com/intact/3d6af5f361c1a44fd878)

Simply changing a few things from:

```
from livestreamer.compat import urljoin, urlparse, urlunparse
from livestreamer.exceptions import PluginError
from livestreamer.plugin import Plugin
from livestreamer.plugin.api import http, validate
from livestreamer.plugin.api.utils import parse_json
from livestreamer.stream import HLSStream
```

To:

```
from streamlink.compat import urljoin, urlparse, urlunparse
from streamlink.exceptions import PluginError
from streamlink.plugin import Plugin
from streamlink.plugin.api import http, validate
from streamlink.plugin.api.utils import parse_json
from streamlink.stream import HLSStream
```

The "plain vanilla" version of Streamlink is working fine with [WinPython 3.5.2.3](https://sourceforge.net/projects/winpython/files/WinPython_3.5/3.5.2.3/) and [PyCryptodome 3.4.5](https://pypi.python.org/pypi/pycryptodome) so far:

![image](https://cloud.githubusercontent.com/assets/19405280/23090448/8790b66a-f5d9-11e6-9156-a8dc424613e6.png)

However, I built the Standalone EXE version of Streamlink Portable and that seemed to be no go:

![image](https://cloud.githubusercontent.com/assets/19405280/23090454/9eb49014-f5d9-11e6-804b-3d44bab42139.png)

Tried [CrunchyRoll](http://www.crunchyroll.com/dragon-ball-super/episode-78-the-gods-of-every-universe-in-shock-losers-erased-in-the-tournament-of-power-727865) instead and it's OK:

![image](https://cloud.githubusercontent.com/assets/19405280/23090643/a1a53860-f5dd-11e6-96c8-006bd8a8c972.png)

Replaced the entire folder %TMP%\RTV_STREAMLINK_FOR_WINDOWS\Streamlink\Crypto with the counterpart taken from that WinPython 3.5.2.3 + PyCryptodome 3.4.5 as mentioned above:

![image](https://cloud.githubusercontent.com/assets/19405280/23090674/bde8f966-f5de-11e6-9fad-b2b200e194d9.png)

There's gotta be a way to integrate PyCryptodome and I'm just wondering how that Standalone EXE should be built in the first place without showing any errors at all.

Thank you very much for your help and have a great day.

**Comment by beardypig** [comment]
I think this is the wrong portable version, it looks like you're after https://github.com/streamlink/streamlink-portable/

**Comment by beardypig** [comment]
I have created a PR to merge the `daisuki` plugin in to `streamlink`: https://github.com/streamlink/streamlink/pull/609. It also adds the feature of being able to automatically include the subtitles by adding `--daisuki-mux-subtitles`.

**Comment by beardypig** [comment]
@starchivore is this fixed with the plugin I streamlink or are you still have trouble with it?

**Comment by starchivore** [comment]
It's all good now, many thanks for your help and please kindly close this.
